#!/bin/bash
# Script for zipping my assignments in my Computer Science Class

name=Collings-Sean 
zip -r $name-$1.zip $1

if [ -z "$2" ]; then
	echo "No Destination specified... Moving into default"
 	mv $name-$1.zip ./$1
else
	echo "Moving to $2"
	mv $name-$1.zip $2	
fi